apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: candle
  namespace: argocd
spec:
  description: Candle platform & services
  sourceRepos:
    - https://github.com/candle/candle-k8s.git
    - https://istio-release.storage.googleapis.com/charts
    - https://strimzi.io/charts/
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://jaegertracing.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
